### ISSUE TITLE
Move Dockerfile to upstream and rename it to Containerfile

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/docker-icingadb#71]
# TODO

* [ ] https://github.com/Icinga/icingadb/pull/756
* [ ] ~https://github.com/Icinga/icinga-go-library/pull/12~ https://github.com/Icinga/icinga-go-library/pull/15
* [ ] make Icinga DB its own entrypoint
* [ ] proceed here

**Comment by oxzi** [comment]
Done in Icinga DB 1.3.0!
